[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<./arduino/*.cpp> +<./.common/*.h>

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<./nodemcuv2/*.c> +<./nodemcuv2/*.cpp> +<./.common/*.h>
